=== angelinn/ComputerStoreXML/src/computer_shop.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT computer-store (parts, sockets, memory-types)>
<!ELEMENT parts (processors, ram-boards, video-cards, hard-drives, motherboards)>
<!ELEMENT processors (processor+) >
<!ELEMENT processor (model, manufacturer, architecture, clock-frequency, cache, threads, available, price) >
<!ATTLIST processor id ID #REQUIRED 
                    socket IDREF #REQUIRED 
                    integrated_video (true | false) "true">

<!ELEMENT model (#PCDATA) >
<!ELEMENT manufacturer (#PCDATA) >
<!ELEMENT architecture (#PCDATA) >
<!ELEMENT clock-frequency (#PCDATA) >
<!ELEMENT cache (levels, memory) >
<!ELEMENT levels (#PCDATA) >
<!ELEMENT memory (#PCDATA) >
<!ELEMENT threads (physical, logical) >
<!ELEMENT physical (#PCDATA) >
<!ELEMENT logical (#PCDATA) >
<!ELEMENT available (#PCDATA) >
<!ELEMENT price (#PCDATA) >

<!ELEMENT ram-boards (ram-board+) >
<!ELEMENT ram-board (manufacturer, memory, frequency, channel, available, price) >
<!ATTLIST ram-board id ID #REQUIRED type IDREF #REQUIRED >
<!ELEMENT frequency (#PCDATA) >
<!ELEMENT channel (#PCDATA) >

<!ELEMENT video-cards (video-card+) >
<!ELEMENT video-card (manufacturer, model, gpu_memory, bus-width, bandwidth, directx, shaders, available, price) >
<!ATTLIST video-card id ID #REQUIRED interface NMTOKEN #REQUIRED >
<!ELEMENT gpu_memory (#PCDATA) >
<!ATTLIST gpu_memory type IDREF #REQUIRED >
<!ELEMENT bus-width (#PCDATA) >
<!ELEMENT bandwidth (#PCDATA) >
<!ELEMENT directx (#PCDATA) >
<!ELEMENT shaders (#PCDATA) >

<!ELEMENT hard-drives (hard-drive+) >
<!ELEMENT hard-drive (manufacturer, drive-memory, speed, size, available, price) >
<!ATTLIST hard-drive id ID #REQUIRED bus NMTOKEN #REQUIRED laptop-compatible (true | false) "false" >
<!ELEMENT drive-memory (amount, type) >
<!ELEMENT amount (#PCDATA) >
<!ELEMENT type (#PCDATA) >
<!ELEMENT speed (#PCDATA) >
<!ELEMENT size (#PCDATA) >

<!ELEMENT motherboards (motherboard+) >
<!ELEMENT motherboard (manufacturer, chipset, available, price) >
<!ATTLIST motherboard id ID #REQUIRED
                      socket-id IDREF #REQUIRED
                      processor IDREF #REQUIRED
                      video-card IDREF #REQUIRED
                      ram-memory IDREF #REQUIRED
                      hard-drive IDREF #REQUIRED>
                      
<!ELEMENT chipset (#PCDATA) >

<!ELEMENT sockets (socket+) >
<!ELEMENT socket (#PCDATA) >
<!ATTLIST socket id ID #REQUIRED >

<!ELEMENT memory-types (memory-type+) >
<!ELEMENT memory-type (#PCDATA) >
<!ATTLIST memory-type id ID #REQUIRED >

=== angelinn/ComputerStoreXML/src/computer_shop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE computer-store SYSTEM "computer_shop.dtd">

<computer-store>
    <parts>
        <processors>
            <processor id="I54200H" socket="A1" integrated_video="true">
                <model>i5 4200H</model>
                <manufacturer>Интел</manufacturer>
                <architecture>Максуел</architecture>
                <clock-frequency>2800</clock-frequency>
                <cache>
                    <levels>3</levels>
                    <memory>3МБ</memory>
                </cache>
                <threads>
                    <physical>2</physical>
                    <logical>4</logical>
                </threads>
                <available>6</available>
                <price>180 лева</price>
            </processor>
        </processors>
        
        <ram-boards>
            <ram-board id="K4" type="D1">
                <manufacturer>Kingston</manufacturer>
                <memory>4ГБ</memory>
                <frequency>1664 мега-херца</frequency>
                <channel>двоен</channel>
                <available>3</available>
                <price>80 лева</price>
            </ram-board>
        </ram-boards>
        
        
        <video-cards>
            <video-card id="GTX850" interface="PCIE-3">
                <manufacturer>NVidia</manufacturer>
                <model>GTX 850m</model>
                <gpu_memory type="GD5">2ГБ</gpu_memory>
                <bus-width>128 бита</bus-width>
                <bandwidth>28.8 ГБ/с</bandwidth>
                <directx>12</directx>
                <shaders>14.4 гига-пиксела/с</shaders>
                <available>3</available>
                <price>80 лева</price>
            </video-card>
        </video-cards>
        
        <hard-drives>
            <hard-drive id="H1" bus="SATA2" laptop-compatible="true">
                <manufacturer>Hitachi</manufacturer>
                <drive-memory>
                    <amount>1ТБ</amount>
                    <type>Флаш</type>
                </drive-memory>
                <speed>1800 оборота/м</speed>
                <size>2.5 инча</size>                
                <available>3</available>
                <price>80 лева</price>
            </hard-drive>
        </hard-drives>
        
        <motherboards>
            <motherboard id="M1"
                         socket-id="S1"
                         processor="I54200H"
                         video-card="GTX850"
                         ram-memory="K4"
                         hard-drive="H1">
                <manufacturer>Foxconn</manufacturer>
                <chipset>Haswell</chipset>
                <available>3</available>
                <price>80 лева</price>
            </motherboard>
        </motherboards>
    </parts>
    
    <sockets>
        <socket id="A1">AM3</socket>
        <socket id="S1">AM2+</socket>
    </sockets>
    <memory-types>
        <memory-type id="D1">DDR1</memory-type>
        <memory-type id="GD5">GDDR5</memory-type>
    </memory-types>
</computer-store>
